### ISSUE TITLE
hardcode is bad practice

### ISSUE THREAD

**Issue by tallinn-learning** [NadiaJoy/Learning-homework4#2]
https://github.com/NadiaJoy/Learning-homework4/blob/52572942f4be15f31bfd93552e5ea39addf83f89/src/Figure.java#L22

use:

  surface = 2 * (this.length  * this.width + this.width * this.height + this.width * this.height);

**Comment by NadiaJoy** [comment]
Fix method calcSurfaceArea (using this.* instead of hard code).

**Comment by tallinn-learning** [comment]
code still has an old implementation for this issue

**Comment by NadiaJoy** [comment]
hello :) check Main branch, please. All changes were pushed yesterday and I can see them. Don’t use the link from your first message here, it redirects me to old commit or smth like it (not Main branch).
